# PaymentDetails REST API Endpoints Manual Tests

@AuthApp.Server_HostAddress = http://localhost:5145/api

# DOCS: https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-9.0

# Get All
GET {{AuthApp.Server_HostAddress}}/payments
Accept: application/json

###

# Get by Id
GET {{AuthApp.Server_HostAddress}}/payments/1
Accept: application/json

###

# Create
POST {{AuthApp.Server_HostAddress}}/payments
Accept: application/json
Content-Type: application/json
{
    "paymentDetailId": 0,    
    "cardOwnerName": "Maktap Abdul",
    "cardNumber": "56456132154",
    "expirationDate": "10/12",
    "securityCode": "456"
}

###

# TODO: Update
PUT {{AuthApp.Server_HostAddress}}/payments/1
Accept: application/json
Content-Type: application/json
{
    "paymentDetailId": 1,
    "cardOwnerName": "Maktap fjk",
    "cardNumber": "56456132154",
    "expirationDate": "10/12",
    "securityCode": "456"
}

###

# TODO: Delete
DELETE {{AuthApp.Server_HostAddress}}/payments/14
Accept: application/json

###